Encoding:
  Enabled: false
LineLength:
  Max: 100
MethodLength:
  Max: 50
HashSyntax:
  Enabled: false

Metrics/ModuleLength:
  Max: 175

Metrics/AbcSize:
  Max: 41

Metrics/PerceivedComplexity:
  Max: 8
